version: '3'
services:
  mysql:
    image: mysql
    ports: 
      - 3305:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gym
    volumes:
      - ./dump:/docker-entrypoint-initdb.d